# Generated by Django 5.2 on 2025-04-07 19:57

import django.core.validators
import django.db.models.deletion
import registration.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application_information', '0002_applicationinformation_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship', models.FileField(blank=True, null=True, upload_to='uploads/sponsorship/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), registration.models.validate_file_size])),
                ('student_copy', models.FileField(blank=True, null=True, upload_to='uploads/student_copy/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), registration.models.validate_file_size])),
                ('recommendation', models.FileField(blank=True, null=True, upload_to='uploads/recommendation/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), registration.models.validate_file_size])),
                ('costsharing', models.FileField(blank=True, null=True, upload_to='uploads/costsharing/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), registration.models.validate_file_size])),
                ('publication', models.FileField(blank=True, null=True, upload_to='uploads/publication/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), registration.models.validate_file_size])),
                ('conceptnote', models.FileField(blank=True, null=True, upload_to='uploads/conceptnote/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), registration.models.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantGAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GAT_No', models.CharField(max_length=12, unique=True)),
                ('GAT_Result', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=15)),
                ('ug_university', models.CharField(max_length=255)),
                ('ug_field_of_study', models.CharField(max_length=255)),
                ('ug_CGPA', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pg_university', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_CGPA', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('application_num', models.CharField(default=registration.models.generate_application_num, max_length=5, unique=True)),
                ('registrar_off_status', models.CharField(max_length=50)),
                ('department_status', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(max_length=50)),
                ('telebirr_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_info', to=settings.AUTH_USER_MODEL)),
                ('dep_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_approvals', to=settings.AUTH_USER_MODEL)),
                ('reg_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrar_approvals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('telebirr_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateField()),
                ('payment_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantProgramSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_information.applicationinformation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
