# Generated by Django 5.2 on 2025-04-07 20:17

import django.core.validators
import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdocumentation',
            name='degree',
            field=models.FileField(blank=True, null=True, upload_to='uploads/degree/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), registration.models.validate_file_size]),
        ),
    ]
