# Generated by Django 5.2 on 2025-04-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_applicantdocumentation_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantinformation',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='department_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='registrar_off_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
