# Generated by Django 5.2 on 2025-04-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_applicantinformation_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantinformation',
            name='grandfather_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
