# Generated by Django 5.2 on 2025-04-08 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_applicantinformation_grandfather_name'),
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantinformation',
            name='sponsorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='sponsorship.sponsorship'),
        ),
    ]
