# Generated by Django 5.2 on 2025-04-08 18:12

import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_applicantinformation_sponsorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinformation',
            name='application_num',
            field=models.CharField(default=registration.models.generate_application_num, max_length=10, unique=True),
        ),
    ]
