# Generated by Django 5.2 on 2025-04-08 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_applicantinformation_application_num'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantgat',
            name='GAT_No',
            field=models.CharField(max_length=12),
        ),
        migrations.AddConstraint(
            model_name='applicantgat',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_gat'),
        ),
    ]
