# Generated by Django 5.2 on 2025-04-08 18:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('department', '0001_initial'),
        ('program', '0001_initial'),
        ('registration', '0007_alter_applicantgat_gat_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprogramselection',
            name='field_of_study',
        ),
        migrations.AddField(
            model_name='applicantprogramselection',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.college'),
        ),
        migrations.AddField(
            model_name='applicantprogramselection',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AddField(
            model_name='applicantprogramselection',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='applicantprogramselection',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.program'),
        ),
    ]
