# Generated by Django 5.2 on 2025-04-08 21:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_information', '0002_applicationinformation_duration'),
        ('registration', '0008_remove_applicantprogramselection_field_of_study_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprogramselection',
            name='college',
        ),
        migrations.RemoveField(
            model_name='applicantprogramselection',
            name='department',
        ),
        migrations.RemoveField(
            model_name='applicantprogramselection',
            name='program',
        ),
        migrations.AddField(
            model_name='applicantprogramselection',
            name='application_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application_information.applicationinformation'),
        ),
        migrations.AddField(
            model_name='applicantprogramselection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicantprogramselection',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='applicantprogramselection',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_program_selection'),
        ),
    ]
