# Generated by Django 5.2 on 2025-04-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_remove_applicantprogramselection_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprogramselection',
            name='priority',
        ),
    ]
