# Generated by Django 5.2 on 2025-04-08 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_information', '0002_applicationinformation_duration'),
        ('registration', '0010_remove_applicantprogramselection_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprogramselection',
            name='application_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application_information.applicationinformation'),
            preserve_default=False,
        ),
    ]
