# Generated by Django 5.2 on 2025-04-08 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_applicantprogramselection_application_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinformation',
            name='pg_CGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(2.0, message='CGPA must be at least 2.0'), django.core.validators.MaxValueValidator(4.0, message='CGPA cannot exceed 4.0')]),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='ug_CGPA',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(2.0, message='CGPA must be at least 2.0'), django.core.validators.MaxValueValidator(4.0, message='CGPA cannot exceed 4.0')]),
        ),
    ]
