# Generated by Django 5.2 on 2025-04-09 08:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_applicantinformation_pg_cgpa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Applicant Payment', 'verbose_name_plural': 'Applicant Payments'},
        ),
        migrations.AddField(
            model_name='applicantpayment',
            name='verification_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of payment verification', null=True),
        ),
        migrations.AddField(
            model_name='applicantpayment',
            name='verification_note',
            field=models.TextField(blank=True, help_text='Notes about payment verification or rejection', null=True),
        ),
        migrations.AddField(
            model_name='applicantpayment',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who verified the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicantpayment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, help_text='Payment amount in ETB', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Payment amount cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='applicantpayment',
            name='payment_date',
            field=models.DateField(help_text='Date of payment'),
        ),
        migrations.AlterField(
            model_name='applicantpayment',
            name='payment_method',
            field=models.CharField(choices=[('TeleBirr', 'TeleBirr'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], help_text='Method used for payment', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicantpayment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Refunded', 'Refunded')], default='Pending', help_text='Current status of the payment', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicantpayment',
            name='payment_time',
            field=models.TimeField(help_text='Time of payment'),
        ),
        migrations.AlterField(
            model_name='applicantpayment',
            name='telebirr_id',
            field=models.CharField(blank=True, help_text='TeleBirr transaction ID (required for TeleBirr payments)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicantpayment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Bank transaction ID (required for bank transfers)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicantpayment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL),
        ),
    ]
