# Generated by Django 5.2 on 2025-04-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinformation',
            name='duration',
            field=models.CharField(blank=True, max_length=1, verbose_name='Duration'),
        ),
    ]
